### ISSUE TITLE
Speedup action

### ISSUE THREAD

**Issue by staabm** [nanasess/setup-php#14]
Consider using apt-fast to speedup action runtime

See e.g. https://www.cyberciti.biz/faq/how-to-speed-up-apt-get-apt-command-ubuntu-linux/

Refs https://github.com/nanasess/setup-php/issues/13#issuecomment-533873775

**Comment by nanasess** [comment]
@staabm 
Implement apt-fast #16
Thanks for the feedback 👍

**Comment by nanasess** [comment]
Merged #16
