### ISSUE TITLE
7.4 is missing xmlwriter and SimpleXML extension to run PHP Code Sniffer

### ISSUE THREAD

**Issue by micgro42** [nanasess/setup-php#29]
I'm trying to switch my workflow for running phpcs from PHP 7.3 to PHP 7.4, but I'm get the following [error](https://github.com/micgro42/dokuwiki-plugin-personaltodo/runs/363340870):

> ERROR: PHP_CodeSniffer requires the tokenizer, xmlwriter and SimpleXML extensions to be enabled. Please enable xmlwriter and SimpleXML.

It works just fine with PHP 7.3.

I'd be happy to help with tracking this down, so if you need any further information/trying things out, then feel free to ask :)

**Comment by nanasess** [comment]
@micgro42 Thanks for the detailed issue, fixed in master branch.

**Comment by nanasess** [comment]
Fixes from #30
