### ISSUE TITLE
Issues with Ubuntu 24.04

### ISSUE THREAD

**Issue by kijin** [nanasess/setup-php#296]
Trying out Ubuntu 24.04 on github actions, ran into a few problems so I'm reporting them here.

Both of the following problems seem to be related to `lib/apt-install-php-ubuntu.sh`

### The apt-fast command is gone in Ubuntu 24.04

```
sudo: apt-fast: command not found
```

Replacing with apt-get seems to fix this problem.
Symlinking `/usr/bin/apt-get` to `/usr/bin/apt-fast` also works.

### Some PHP modules are missing

PHP 8.2 and 8.3 install and work perfectly.

PHP 8.1 and below seem to be packaged differently in Ubuntu 24.04.

```
E: Unable to locate package php8.1-dev
E: Couldn't find any package by glob 'php8.1-dev'
E: Couldn't find any package by regex 'php8.1-dev'
E: Unable to locate package php8.1-phpdbg
E: Couldn't find any package by glob 'php8.1-phpdbg'
E: Couldn't find any package by regex 'php8.1-phpdbg'
E: Unable to locate package php8.1-intl
E: Couldn't find any package by glob 'php8.1-intl'
E: Couldn't find any package by regex 'php8.1-intl'
E: Unable to locate package php8.1-xml
E: Couldn't find any package by glob 'php8.1-xml'
E: Couldn't find any package by regex 'php8.1-xml'
```

```
E: Unable to locate package php8.0-dev
E: Couldn't find any package by glob 'php8.0-dev'
E: Couldn't find any package by regex 'php8.0-dev'
E: Unable to locate package php8.0-phpdbg
E: Couldn't find any package by glob 'php8.0-phpdbg'
E: Couldn't find any package by regex 'php8.0-phpdbg'
E: Unable to locate package php8.0-intl
E: Couldn't find any package by glob 'php8.0-intl'
E: Couldn't find any package by regex 'php8.0-intl'
E: Unable to locate package php8.0-xml
E: Couldn't find any package by glob 'php8.0-xml'
E: Couldn't find any package by regex 'php8.0-xml'
```

Thanks for your great work!

**Comment by sl0wik** [comment]
Is there any solution that can be applied to the workflow file?

**Comment by nanasess** [comment]
Will be fixed soon.
Can you substitute https://github.com/shivammathur/setup-php?
If not, please let us know why.🙇‍♂️

**Comment by nanasess** [comment]
@kijin 
Although I have not been able to find much time recently, I will continue to maintain this package.
Thanks for liking it!

**Comment by nanasess** [comment]
@kijin 
Thank you all for your contributions!, Fixed version has been pre-released.
https://github.com/nanasess/setup-php/releases/tag/v4.1.0

**Comment by kijin** [comment]
Works like a charm, thanks!
