### ISSUE TITLE
PHP 7.0 missing ext-xmlwriter for PHP Codesniffer

### ISSUE THREAD

**Issue by jdpedrie** [nanasess/setup-php#33]
Running `composer install` using PHP 7.0 raises the following error:

```
squizlabs/php_codesniffer 3.5.4 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.
```

I see this is similar to #29, and it was fixed by specifically targeting PHP 7.4. In my build matrix, the PHP 7.4 build works fine, so the existing fix seems to be good, but perhaps it should be promoted to run in all versions rather than just 7.4.

Thanks for the useful tool!

**Comment by nanasess** [comment]
@jdpedrie Welcome to setup-php, thanks for the detailed issue and feedback🙏
Merged from #34, Thank you so much!
