### ISSUE TITLE
How can I install/enable a PHP extension using this package?

### ISSUE THREAD

**Issue by nelson6e65** [nanasess/setup-php#47]
For example, I require `ext-mbstring`.

I'm using `nanasess/setup-php@v3.0.5`

**Comment by nelson6e65** [comment]
Hmm... I see is already included:

https://github.com/nanasess/setup-php/blob/48858e2da37dc6d55d7eb4b6a80011ed7eba5ec5/lib/apt-install-php-ubuntu.sh#L31

But I'm getting this error:

```
phpunit/phpunit[dev-master, 9.3.0, ..., 9.4.x-dev] require ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
```

(Ref: https://github.com/nelson6e65/php_nml/runs/1467382317?check_suite_focus=true#step:5:59)

**Comment by nanasess** [comment]
@nelson6e65 Sorry, PHP8  now support on Ubuntu 20.04 only.
Support for 18.04 please wait🙏

**Comment by nanasess** [comment]
@nelson6e65 Added support for PHP8 on Ubuntu 18.04 https://github.com/nanasess/setup-php/releases/tag/v3.0.6

**Comment by nelson6e65** [comment]
Nice. Thanks. Good job.

It is confused the that `ubuntu-latest` is targeting Ubuntu 18 instead of 20. 😅
