### ISSUE TITLE
Running nanasess/setup-php@v3 with php 8.1 is slower

### ISSUE THREAD

**Issue by reindert-vetter** [nanasess/setup-php#65]
`Running nanasess/setup-php@v3` with PHP 7.4 takes about 30 seconds. With php 8.1 it takes me more than 2 minutes.

At first I thought that was because GitHub had actions [8.1.1 preinstalled](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#php) (and not 8.1.2), but even if I change it to 8.1.1, it takes longer. Do you have any idea why this is and how we can speed it up?

**Comment by nanasess** [comment]
It may be taking a long time to update the related extensions.
Fixing the following versions to 8.1.1 may resolve the issue.
https://github.com/nanasess/setup-php/blob/b399285de0dc4ba74e147d8f5fc30c39c4b2f78f/src/installer.ts#L64

**Comment by reindert-vetter** [comment]
![image](https://user-images.githubusercontent.com/16726304/152175868-f3e7ac10-5f0c-47a8-aff5-8ec026174cf4.png)
Unfortunately: He is still busy after 7 minutes. Do you have any other ideas? Otherwise I'll leave it for now, maybe it will sort itself out in the future.

**Comment by reindert-vetter** [comment]
Oh, sorry I didn't report it. The above was indeed with a specific version. If I modify the installer.ts, it still wants to install all extensions separately.
![image](https://user-images.githubusercontent.com/16726304/152180085-ac6ba53d-cdae-4211-99a5-e2fbdcc156f7.png)

**Comment by reindert-vetter** [comment]
I will close this for now. We can open it again if we have an idea that we can fix this ourselves.

**Comment by reindert-vetter** [comment]
![image](https://user-images.githubusercontent.com/16726304/152558187-9bd0980b-7dfc-4134-9789-d7c762638f87.png)
@nanasess Now it works fine. (I haven't changed anything). :raised_eyebrow:

**Comment by nanasess** [comment]
@reindert-vetter I'll try to verify that, too🙇‍♂️
